exports.seed = (knex, Promise)=>{
  return knex('exercises').del()
    .then( ()=>{
      return knex('exercises').insert([
        {exercise_id:1,exercise_name:'assisted squat'},
        {exercise_id:2,exercise_name:'sideprone lift'},
        {exercise_id:3,exercise_name:'parallel squat'},
        {exercise_id:4,exercise_name:'kneeling side lift'},
        {exercise_id:5,exercise_name:'full squat'},
        {exercise_id:6,exercise_name:'kneeling circle'},
        {exercise_id:7,exercise_name:'elevated deck squat'},
        {exercise_id:8,exercise_name:'kneeling parallel slide'},
        {exercise_id:9,exercise_name:'deck squat'},
        {exercise_id:10,exercise_name:'skiers'},
        {exercise_id:11,exercise_name:'cossack squat'},
        {exercise_id:12,exercise_name:'twisting squats'},
        {exercise_id:13,exercise_name:'side-to-side squat'},
        {exercise_id:14,exercise_name:'inside squat'},
        {exercise_id:15,exercise_name:'speed skater squat'},
        {exercise_id:16,exercise_name:'natural leg extension'},
        {exercise_id:17,exercise_name:'hawaiian squat'},
        {exercise_id:18,exercise_name:'shoulder bridge leg curl'},
        {exercise_id:19,exercise_name:'static single leg squat'},
        {exercise_id:20,exercise_name:'single leg bridge curl'},
        {exercise_id:21,exercise_name:'negative single leg squat'},
        {exercise_id:22,exercise_name:'natural leg curl'},
        {exercise_id:23,exercise_name:'rocking single leg squat'},
        {exercise_id:24,exercise_name:'natural glute ham raise'},
        {exercise_id:25,exercise_name:'single leg squat'},
        {exercise_id:26,exercise_name:'glute ham raise'},
        {exercise_id:27,exercise_name:'lunge with 25% body weight'},
        {exercise_id:28,exercise_name:'arch up + 10lbs'},
        {exercise_id:29,exercise_name:'lunge with 50% body weight'},
        {exercise_id:30,exercise_name:'arch up + 25lbs'},
        {exercise_id:31,exercise_name:'lunge with 75% body weight'},
        {exercise_id:32,exercise_name:'arch up + 35lbs'},
        {exercise_id:33,exercise_name:'lunge with 100% body weight'},
        {exercise_id:34,exercise_name:'arch up + 45lbs'},
      ]);
    });
};
