const allExercises = require('../data/allExercises')

exports.seed = (knex, Promise)=>{
  return knex('exercises').del()
    .then( ()=>{
      return knex('exercises').insert(allExercises);
      // return knex('exercises').insert([
      //   {exercise_id:1,exercise_name:'assisted squat'},
      //   {exercise_id:2,exercise_name:'parallel squat'},
      //   {exercise_id:3,exercise_name:'full squat'},
      //   {exercise_id:4,exercise_name:'elevated deck squat'},
      //   {exercise_id:5,exercise_name:'deck squat'},
      //   {exercise_id:6,exercise_name:'cossack squat'},
      //   {exercise_id:7,exercise_name:'side-to-side squat'},
      //   {exercise_id:8,exercise_name:'speed skater squat'},
      //   {exercise_id:9,exercise_name:'hawaiian squat'},
      //   {exercise_id:10,exercise_name:'static single leg squat'},
      //   {exercise_id:11,exercise_name:'negative single leg squat'},
      //   {exercise_id:12,exercise_name:'rocking single leg squat'},
      //   {exercise_id:13,exercise_name:'single leg squat'},
      //   {exercise_id:14,exercise_name:'lunge with 25% body weight'},
      //   {exercise_id:15,exercise_name:'lunge with 50% body weight'},
      //   {exercise_id:16,exercise_name:'lunge with 75% body weight'},
      //   {exercise_id:17,exercise_name:'lunge with 100% body weight'},
      //   {exercise_id:18,exercise_name:'sideprone lift'},
      //   {exercise_id:19,exercise_name:'kneeling side lift'},
      //   {exercise_id:20,exercise_name:'kneeling circle'},
      //   {exercise_id:21,exercise_name:'kneeling parallel slide'},
      //   {exercise_id:22,exercise_name:'skiers'},
      //   {exercise_id:23,exercise_name:'twisting squats'},
      //   {exercise_id:24,exercise_name:'inside squat'},
      //   {exercise_id:25,exercise_name:'natural leg extension'},
      //   {exercise_id:26,exercise_name:'shoulder bridge leg curl'},
      //   {exercise_id:27,exercise_name:'single leg bridge curl'},
      //   {exercise_id:28,exercise_name:'natural leg curl'},
      //   {exercise_id:29,exercise_name:'natural glute ham raise'},
      //   {exercise_id:30,exercise_name:'glute ham raise'},
      //   {exercise_id:31,exercise_name:'arch up + 10lbs'},
      //   {exercise_id:32,exercise_name:'arch up + 25lbs'},
      //   {exercise_id:33,exercise_name:'arch up + 35lbs'},
      //   {exercise_id:34,exercise_name:'arch up + 45lbs'},
      //   {exercise_id:35,exercise_name:'bent hollow body hold'},
      //   {exercise_id:36,exercise_name:'bent hollow body rock'},
      //   {exercise_id:37,exercise_name:'straddle hollow body hold'},
      //   {exercise_id:38,exercise_name:'straddle hollow body rock'},
      //   {exercise_id:39,exercise_name:'hollow body hold'},
      //   {exercise_id:40,exercise_name:'hollow body rock'},
      //   {exercise_id:41,exercise_name:'negative body lever straddle'},
      //   {exercise_id:42,exercise_name:'negative body lever single leg'},
      //   {exercise_id:43,exercise_name:'negative body lever'},
      //   {exercise_id:44,exercise_name:'body lever'},
      //   {exercise_id:45,exercise_name:'negative vertical body lever'},
      //   {exercise_id:46,exercise_name:'vertical body lever'},
      //   {exercise_id:47,exercise_name:'single bar inverted hang'},
      //   {exercise_id:48,exercise_name:'kip extension'},
      //   {exercise_id:49,exercise_name:'negative front pull'},
      //   {exercise_id:50,exercise_name:'front pull'},
      //   {exercise_id:51,exercise_name:'open front lever'},
      //   {exercise_id:52,exercise_name:'open front lever bent single leg'},
      //   {exercise_id:53,exercise_name:'open front lever bent double leg'},
      //   {exercise_id:54,exercise_name:'1/2 straddle front lever'},
      //   {exercise_id:55,exercise_name:'1/2 straddle front lever scissor'},
      //   {exercise_id:56,exercise_name:'1/2 front lever'},
      //   {exercise_id:57,exercise_name:'single leg straddle front lever '},
      //   {exercise_id:58,exercise_name:'straddle front lever'},
      //   {exercise_id:59,exercise_name:'single leg front lever'},
      //   {exercise_id:60,exercise_name:'1/2 front pull'},
      //   {exercise_id:61,exercise_name:'front lever'},
      //   {exercise_id:62,exercise_name:'cat cow'},
      //   {exercise_id:63,exercise_name:'table'},
      //   {exercise_id:64,exercise_name:'table rock'},
      //   {exercise_id:65,exercise_name:'table inside out'},
      //   {exercise_id:66,exercise_name:'shoulder bridge'},
      //   {exercise_id:67,exercise_name:'shoulder bridge rock'},
      //   {exercise_id:68,exercise_name:'seal rocks'},
      //   {exercise_id:69,exercise_name:'suspended seal'},
      //   {exercise_id:70,exercise_name:'seal pushup'},
      //   {exercise_id:71,exercise_name:'elbow bridge'},
      //   {exercise_id:72,exercise_name:'elbow bridge single leg'},
      //   {exercise_id:73,exercise_name:'elbow bridge rock'},
      //   {exercise_id:74,exercise_name:'low bridge'},
      //   {exercise_id:75,exercise_name:'low bridge single leg'},
      //   {exercise_id:76,exercise_name:'low bridge rock'},
      //   {exercise_id:77,exercise_name:'low bridge inside out'},
      //   {exercise_id:78,exercise_name:'mid bridge'},
      //   {exercise_id:79,exercise_name:'mid bridge single leg'},
      //   {exercise_id:80,exercise_name:'mid bridge double leg'},
      //   {exercise_id:81,exercise_name:'mid bridge inside out'},
      //   {exercise_id:82,exercise_name:'bridge'},
      //   {exercise_id:83,exercise_name:'bridge pushups'},
      //   {exercise_id:84,exercise_name:'bridge inside out'},
      //   {exercise_id:85,exercise_name:'single leg lift bridge'},
      //   {exercise_id:86,exercise_name:'single arm lift bridge'},
      //   {exercise_id:87,exercise_name:'bridge wall walk'},
      //   {exercise_id:88,exercise_name:'1/2 back limber'},
      //   {exercise_id:89,exercise_name:'seated russian twist'},
      //   {exercise_id:90,exercise_name:'elbow side plank'},
      //   {exercise_id:91,exercise_name:'side over arch'},
      //   {exercise_id:92,exercise_name:'arch up'},
      //   {exercise_id:93,exercise_name:'twisting arch up'},
      //   {exercise_id:94,exercise_name:'circle arch up'},
      //   {exercise_id:95,exercise_name:'straddle reverse leg lift'},
      //   {exercise_id:96,exercise_name:'reverse leg lift'},
      //   {exercise_id:97,exercise_name:'stall bar reverse leg lift'},
      //   {exercise_id:98,exercise_name:'1/2 windshield wiper'},
      //   {exercise_id:99,exercise_name:'windshield wiper'},
      //   {exercise_id:100,exercise_name:'side arch body hold'},
      //   {exercise_id:101,exercise_name:'side arch body rock'},
      //   {exercise_id:102,exercise_name:'arch body hold'},
      //   {exercise_id:103,exercise_name:'arch body rock'},
      //   {exercise_id:104,exercise_name:'side lever block'},
      //   {exercise_id:105,exercise_name:'side lever block twist'},
      //   {exercise_id:106,exercise_name:'side lever block press'},
      //   {exercise_id:107,exercise_name:'side lever inverted hold'},
      //   {exercise_id:108,exercise_name:'straddle side lever pull'},
      //   {exercise_id:109,exercise_name:'scissoring side lever pull'},
      //   {exercise_id:110,exercise_name:'closed side lever pull'},
      //   {exercise_id:111,exercise_name:'negative side lever pull'},
      //   {exercise_id:112,exercise_name:'side lever pull'},
      //   {exercise_id:113,exercise_name:'side lever'},
      //   {exercise_id:114,exercise_name:'standing hip circle'},
      //   {exercise_id:115,exercise_name:'standing trunk circle'},
      //   {exercise_id:116,exercise_name:'elbow bounces'},
      //   {exercise_id:117,exercise_name:'standing weighed oblique stretch'},
      //   {exercise_id:118,exercise_name:'standing weighed oblique reps'},
      //   {exercise_id:119,exercise_name:'outside inside outside back'},
      //   {exercise_id:120,exercise_name:'around the world'},
      //   {exercise_id:121,exercise_name:'horizontal windmill'},
      //   {exercise_id:122,exercise_name:'2 forward 2 twist'},
      //   {exercise_id:123,exercise_name:'bent hurdler hold'},
      //   {exercise_id:124,exercise_name:'bent hurdler rep'},
      //   {exercise_id:125,exercise_name:'bent hurdler twist'},
      //   {exercise_id:126,exercise_name:'hurdler static'},
      //   {exercise_id:127,exercise_name:'hurdler rep'},
      //   {exercise_id:128,exercise_name:'hurdler twist'},
      //   {exercise_id:129,exercise_name:'bent pancake static'},
      //   {exercise_id:130,exercise_name:'bent pancake rep'},
      //   {exercise_id:131,exercise_name:'bent pancake twist'},
      //   {exercise_id:132,exercise_name:'pancake side static'},
      //   {exercise_id:133,exercise_name:'pancake side rep'},
      //   {exercise_id:134,exercise_name:'pancake side twist'},
      //   {exercise_id:135,exercise_name:'pancake side to side rep'},
      //   {exercise_id:136,exercise_name:'pancake toe touch'},
      //   {exercise_id:137,exercise_name:'overhead/weighted/loaded pancake side static'},
      //   {exercise_id:138,exercise_name:'weighted pancake side rep'},
      //   {exercise_id:139,exercise_name:'scapular shrugs'},
      //   {exercise_id:140,exercise_name:'forearm plank'},
      //   {exercise_id:141,exercise_name:'plank'},
      //   {exercise_id:142,exercise_name:'single-arm plank'},
      //   {exercise_id:143,exercise_name:'planche lean'},
      //   {exercise_id:144,exercise_name:'elevated planche lean'},
      //   {exercise_id:145,exercise_name:'elevated planche bounce'},
      //   {exercise_id:146,exercise_name:'frog stand'},
      //   {exercise_id:147,exercise_name:'advanced frog stand'},
      //   {exercise_id:148,exercise_name:'tuck planche'},
      //   {exercise_id:149,exercise_name:'open planche'},
      //   {exercise_id:150,exercise_name:'open planche single leg exension'},
      //   {exercise_id:151,exercise_name:'open planche double leg extension'},
      //   {exercise_id:152,exercise_name:'1/2 straddle planche'},
      //   {exercise_id:153,exercise_name:'1/2 straddle planche single extension'},
      //   {exercise_id:154,exercise_name:'1/2 straddle planche double extension'},
      //   {exercise_id:155,exercise_name:'scissoring straddle planche'},
      //   {exercise_id:156,exercise_name:'straddle planche'},
      //   {exercise_id:157,exercise_name:'swivel hips'},
      //   {exercise_id:158,exercise_name:'straddle running man'},
      //   {exercise_id:159,exercise_name:'straddle modified reverse hyper'},
      //   {exercise_id:160,exercise_name:'straddle donkey kick'},
      //   {exercise_id:161,exercise_name:'prone half straddle planche hold'},
      //   {exercise_id:162,exercise_name:'prone half straddle planche single leg extension'},
      //   {exercise_id:163,exercise_name:'prone half straddle planche double leg extension'},
      //   {exercise_id:164,exercise_name:'bent arm half straddle planche hold'},
      //   {exercise_id:165,exercise_name:'bent arm half straddle planche single leg extension'},
      //   {exercise_id:166,exercise_name:'bent arm half straddle planche double leg extension'},
      //   {exercise_id:167,exercise_name:'bent arm straddle planche single leg hold'},
      //   {exercise_id:168,exercise_name:'bent arm straddle planche'},
      //   {exercise_id:169,exercise_name:'SAC 1'},
      //   {exercise_id:170,exercise_name:'SAC 2'},
      //   {exercise_id:171,exercise_name:'SAC 3'},
      //   {exercise_id:172,exercise_name:'SAC 4'},
      //   {exercise_id:173,exercise_name:'SAC 5'},
      //   {exercise_id:174,exercise_name:'SAC 6'},
      //   {exercise_id:175,exercise_name:'incline push up'},
      //   {exercise_id:176,exercise_name:'pushup'},
      //   {exercise_id:177,exercise_name:'pseudo planche pushup'},
      //   {exercise_id:178,exercise_name:'bench dip'},
      //   {exercise_id:179,exercise_name:'negative parallel bar dip'},
      //   {exercise_id:180,exercise_name:'parallel bar dip'},
      //   {exercise_id:181,exercise_name:'single bar dip'},
      //   {exercise_id:182,exercise_name:'undergrip single bar dip'},
      //   {exercise_id:183,exercise_name:'korean dip'},
      //   {exercise_id:184,exercise_name:'undergrip korean dip'},
      //   {exercise_id:185,exercise_name:'russian dip'},
      //   {exercise_id:186,exercise_name:'russian L dip'},
      //   {exercise_id:187,exercise_name:'ring dip'},
      //   {exercise_id:188,exercise_name:'bulgarian ring dip'},
      //   {exercise_id:189,exercise_name:'box headstand pushups'},
      //   {exercise_id:190,exercise_name:'negative headstand pushup'},
      //   {exercise_id:191,exercise_name:'free hespu'},
      //   {exercise_id:192,exercise_name:'elevated headstand pushup'},
      //   {exercise_id:193,exercise_name:'wall handstand pushup'},
      //   {exercise_id:194,exercise_name:'pseudo planche pushup +'},
      //   {exercise_id:195,exercise_name:'planche dip'},
      //   {exercise_id:196,exercise_name:'modified planche pushup'},
      //   {exercise_id:197,exercise_name:'chest roll 1'},
      //   {exercise_id:198,exercise_name:'chest roll 2'},
      //   {exercise_id:199,exercise_name:'chest roll 3'},
      //   {exercise_id:200,exercise_name:'chest roll 4'},
      //   {exercise_id:201,exercise_name:'chest roll 5'},
      //   {exercise_id:202,exercise_name:'chest roll 6'},
      //   {exercise_id:203,exercise_name:'1/2 hollow back press'},
      //   {exercise_id:204,exercise_name:'hollow back press'},
      //   {exercise_id:205,exercise_name:'german arm swing'},
      //   {exercise_id:206,exercise_name:'xiaopeng forward'},
      //   {exercise_id:207,exercise_name:'xiaopeng backward'},
      //   {exercise_id:208,exercise_name:'double arm circle backward'},
      //   {exercise_id:209,exercise_name:'double arm circle forward'},
      //   {exercise_id:210,exercise_name:'single arm bent cat'},
      //   {exercise_id:211,exercise_name:'static cat'},
      //   {exercise_id:212,exercise_name:'rocking cat'},
      //   {exercise_id:213,exercise_name:'reach underneath static'},
      //   {exercise_id:214,exercise_name:'reach underneath rep'},
      //   {exercise_id:215,exercise_name:'prone side chest static '},
      //   {exercise_id:216,exercise_name:'prone side chest rep'},
      //   {exercise_id:217,exercise_name:'prone capsule static'},
      //   {exercise_id:218,exercise_name:'prone capsule rep'},
      //   {exercise_id:219,exercise_name:'bent arm prone static'},
      //   {exercise_id:220,exercise_name:'bent arm prone rep'},
      //   {exercise_id:221,exercise_name:'clasped static'},
      //   {exercise_id:222,exercise_name:'clasped rep'},
      //   {exercise_id:223,exercise_name:'chicken wing static'},
      //   {exercise_id:224,exercise_name:'chicken wing rep'},
      //   {exercise_id:225,exercise_name:'vertical chicken static'},
      //   {exercise_id:226,exercise_name:'prone retraction one'},
      //   {exercise_id:227,exercise_name:'prone retraction two'},
      //   {exercise_id:228,exercise_name:'prone external rotation one'},
      //   {exercise_id:229,exercise_name:'prone external rotation two'},
      //   {exercise_id:230,exercise_name:'prone rotation three'},
      //   {exercise_id:231,exercise_name:'prone rotation four'},
      //   {exercise_id:232,exercise_name:'prone external rotation three'},
      //   {exercise_id:233,exercise_name:'prone external rotation four'},
      //   {exercise_id:234,exercise_name:'cuban press'},
      //   {exercise_id:235,exercise_name:'tuck-up'},
      //   {exercise_id:236,exercise_name:'straddle up'},
      //   {exercise_id:237,exercise_name:'v-ups'},
      //   {exercise_id:238,exercise_name:'1/2 tuck hanging leg lift'},
      //   {exercise_id:239,exercise_name:'1/2 hanging leg lift'},
      //   {exercise_id:240,exercise_name:'negative hanging leg lift'},
      //   {exercise_id:241,exercise_name:'hanging leg lift'},
      //   {exercise_id:242,exercise_name:'undergrip hanging leg lift'},
      //   {exercise_id:243,exercise_name:'v-to-L hanging leg lift'},
      //   {exercise_id:244,exercise_name:'1/2 L-sit'},
      //   {exercise_id:245,exercise_name:'1/2 L-sit single leg extension'},
      //   {exercise_id:246,exercise_name:'1/2 L-sit double leg extension'},
      //   {exercise_id:247,exercise_name:'L-sit scissors'},
      //   {exercise_id:248,exercise_name:'L-sit'},
      //   {exercise_id:249,exercise_name:'1/2 straddle L'},
      //   {exercise_id:250,exercise_name:'1/2 straddle L single extension'},
      //   {exercise_id:251,exercise_name:'1/2 straddle L double extension'},
      //   {exercise_id:252,exercise_name:'straddle L'},
      //   {exercise_id:253,exercise_name:'elevated reverse plank'},
      //   {exercise_id:254,exercise_name:'1/2 middle split hold'},
      //   {exercise_id:255,exercise_name:'1/2 middle split hold single extension'},
      //   {exercise_id:256,exercise_name:'1/2 middle split hold double extension'},
      //   {exercise_id:257,exercise_name:'middle split hold'},
      //   {exercise_id:258,exercise_name:'manna press'},
      //   {exercise_id:259,exercise_name:'manna'},
      //   {exercise_id:260,exercise_name:'stiff leg windmill'},
      //   {exercise_id:261,exercise_name:'jefferson curl'},
      //   {exercise_id:262,exercise_name:'pike lean'},
      //   {exercise_id:263,exercise_name:'standing weighed pike hang'},
      //   {exercise_id:264,exercise_name:'vertical pike walk'},
      //   {exercise_id:265,exercise_name:'vertical pike pull'},
      //   {exercise_id:266,exercise_name:'vertical pike hang'},
      //   {exercise_id:267,exercise_name:'bench pike hang'},
      //   {exercise_id:268,exercise_name:'bench pike squat'},
      //   {exercise_id:269,exercise_name:'seated pike lift'},
      //   {exercise_id:270,exercise_name:'seated pike pulses'},
      //   {exercise_id:271,exercise_name:'straddle jefferson curl'},
      //   {exercise_id:272,exercise_name:'standing weighed straddle hang'},
      //   {exercise_id:273,exercise_name:'straddle lean'},
      //   {exercise_id:274,exercise_name:'vertical straddle walk'},
      //   {exercise_id:275,exercise_name:'vertical straddle pull'},
      //   {exercise_id:276,exercise_name:'vertical straddle hang'},
      //   {exercise_id:277,exercise_name:'seated straddle lift'},
      //   {exercise_id:278,exercise_name:'seated straddle pulse'},
      //   {exercise_id:279,exercise_name:'shoulder extension pull'},
      //   {exercise_id:280,exercise_name:'should extension static'},
      //   {exercise_id:281,exercise_name:'manna wall slide'},
      //   {exercise_id:282,exercise_name:'weighed shoulder extension pull'},
      //   {exercise_id:283,exercise_name:'weighted shoulder extension hang'},
      //   {exercise_id:284,exercise_name:'manna swing'},
      //   {exercise_id:285,exercise_name:'incline row'},
      //   {exercise_id:286,exercise_name:'ground row'},
      //   {exercise_id:287,exercise_name:'elevated row'},
      //   {exercise_id:288,exercise_name:'bulgarian row'},
      //   {exercise_id:289,exercise_name:'hinge row'},
      //   {exercise_id:290,exercise_name:'bent arm chin hang'},
      //   {exercise_id:291,exercise_name:'negative pull-up'},
      //   {exercise_id:292,exercise_name:'pull-up'},
      //   {exercise_id:293,exercise_name:'L chin-up'},
      //   {exercise_id:294,exercise_name:'bulgarian pull-up'},
      //   {exercise_id:295,exercise_name:'bulgarian L pull-up'},
      //   {exercise_id:296,exercise_name:'wide grip pull-up'},
      //   {exercise_id:297,exercise_name:'wide grip beind-the-neck pull-up'},
      //   {exercise_id:298,exercise_name:'wide grip L pull-up'},
      //   {exercise_id:299,exercise_name:'pullover'},
      //   {exercise_id:300,exercise_name:'naners'},
      //   {exercise_id:301,exercise_name:'tops pull'},
      //   {exercise_id:302,exercise_name:'yewkis'},
      //   {exercise_id:303,exercise_name:'1/2 front lever pull'},
      //   {exercise_id:304,exercise_name:'front lever pull'},
      //   {exercise_id:305,exercise_name:'cicle front lever pull'},
      //   {exercise_id:306,exercise_name:'czech 1'},
      //   {exercise_id:307,exercise_name:'czech 2'},
      //   {exercise_id:308,exercise_name:'czech 3'},
      //   {exercise_id:309,exercise_name:'czech 4'},
      //   {exercise_id:310,exercise_name:'rope climb'},
      //   {exercise_id:311,exercise_name:'rope climb 2'},
      //   {exercise_id:312,exercise_name:'one arm upright lat lean'},
      //   {exercise_id:313,exercise_name:'bent sideways lat stretch'},
      //   {exercise_id:314,exercise_name:'bent twisting lat static'},
      //   {exercise_id:315,exercise_name:'bent twisting lat reps'},
      //   {exercise_id:316,exercise_name:'overgrip bent lean'},
      //   {exercise_id:317,exercise_name:'overgrip bent pull'},
      //   {exercise_id:318,exercise_name:'undergrip bent lean'},
      //   {exercise_id:319,exercise_name:'overgrip one arm lean'},
      //   {exercise_id:320,exercise_name:'overgrip one arm pull'},
      //   {exercise_id:321,exercise_name:'perpendicular lat static'},
      //   {exercise_id:322,exercise_name:'perpendicular lat rep'},
      //   {exercise_id:323,exercise_name:'shoulder distraction one'},
      //   {exercise_id:324,exercise_name:'shoulder distraction two'},
      //   {exercise_id:325,exercise_name:'shoulder distraction three'},
      //   {exercise_id:326,exercise_name:'shoulder distraction four'},
      //   {exercise_id:327,exercise_name:'st lat 1'},
      //   {exercise_id:328,exercise_name:'st lat 2'},
      //   {exercise_id:329,exercise_name:'st lat 3'},
      //   {exercise_id:330,exercise_name:'st lat 4'},
      //   {exercise_id:331,exercise_name:'undergrip hang'},
      //   {exercise_id:332,exercise_name:'one arm overgrip hang'},
      //   {exercise_id:333,exercise_name:'scap pull'},
      //   {exercise_id:334,exercise_name:'one arm assisted rotation'},
      //   {exercise_id:335,exercise_name:'one arm rotation'},
      //   {exercise_id:336,exercise_name:'one arm scap pull'},
      //   {exercise_id:337,exercise_name:'lat fly'},
      //   {exercise_id:338,exercise_name:'lat fly 2'},
      // ]);
    });
  };
  