/*
*******************LEGEND*******************
const progression_exercise_mastery_mapping = {
  progression_id:{
    sequence_number:{
      mastery_id_strength:,
      mastery_id_mobility:
    }
  }
}
*******************LEGEND*******************
*/
// const progression_mapping = {
//   1:{
//     1:{
//       mastery_id_strength:6,
//       mastery_id_mobility:2
//     },
//     2:{
//       mastery_id_strength:6,
//       mastery_id_mobility:2
//     },
//     3:{
//       mastery_id_strength:5,
//       mastery_id_mobility:2
//     },
//     4:{
//       mastery_id_strength:5,
//       mastery_id_mobility:2
//     },
//     5:{
//       mastery_id_strength:5,
//       mastery_id_mobility:5
//     },
//     6:{
//       mastery_id_strength:5,
//       mastery_id_mobility:3
//     },
//     7:{
//       mastery_id_strength:5,
//       mastery_id_mobility:3
//     },
//     8:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     9:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     10:{
//       mastery_id_strength:13,
//       mastery_id_mobility:3
//     },
//     11:{
//       mastery_id_strength:10,
//       mastery_id_mobility:3
//     },
//     12:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     13:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     14:{
//       mastery_id_strength:5,
//       mastery_id_mobility:3
//     },
//     15:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     16:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     17:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//   },
//   2:{
//     1:{
//       mastery_id_strength:15,
//       mastery_id_mobility:3
//     },
//     2:{
//       mastery_id_strength:8,
//       mastery_id_mobility:13
//     },
//     3:{
//       mastery_id_strength:15,
//       mastery_id_mobility:3
//     },
//     4:{
//       mastery_id_strength:8,
//       mastery_id_mobility:3
//     },
//     5:{
//       mastery_id_strength:15,
//       mastery_id_mobility:3
//     },
//     6:{
//       mastery_id_strength:8,
//       mastery_id_mobility:3
//     },
//     7:{
//       mastery_id_strength:10,
//       mastery_id_mobility:3
//     },
//     8:{
//       mastery_id_strength:10,
//       mastery_id_mobility:13
//     },
//     9:{
//       mastery_id_strength:10,
//       mastery_id_mobility:3
//     },
//     10:{
//       mastery_id_strength:3,
//       mastery_id_mobility:9
//     },
//     11:{
//       mastery_id_strength:10,
//       mastery_id_mobility:18
//     },
//     12:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     13:{
//       mastery_id_strength:13,
//       mastery_id_mobility:9
//     },
//     14:{
//       mastery_id_strength:3,
//       mastery_id_mobility:18
//     },
//     15:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     16:{
//       mastery_id_strength:3,
//       mastery_id_mobility:1
//     },
//     17:{
//       mastery_id_strength:7,
//       mastery_id_mobility:9
//     },
//     18:{
//       mastery_id_strength:5,
//       mastery_id_mobility:5
//     },
//     19:{
//       mastery_id_strength:3,
//       mastery_id_mobility:3
//     },
//     20:{
//       mastery_id_strength:9,
//       mastery_id_mobility:1
//     },
//     21:{
//       mastery_id_strength:3,
//       mastery_id_mobility:9
//     },
//     22:{
//       mastery_id_strength:9,
//       mastery_id_mobility:3
//     },
//     23:{
//       mastery_id_strength:9,
//       mastery_id_mobility:1
//     },
//     24:{
//       mastery_id_strength:9,
//       mastery_id_mobility:5
//     },
//     25:{
//       mastery_id_strength:9,
//       mastery_id_mobility:5
//     },
//     26:{
//       mastery_id_strength:3,
//       mastery_id_mobility:1
//     },
//     27:{
//       mastery_id_strength:9,
//       mastery_id_mobility:1
//     },
//   },
//   3:{
//     1:{
//       mastery_id_strength:7,
//       mastery_id_mobility:5
//     },
//     2:{
//       mastery_id_strength:18,
//       mastery_id_mobility:5
//     },
//     3:{
//       mastery_id_strength:18,
//       mastery_id_mobility:5
//     },
//     4:{
//       mastery_id_strength:5,
//       mastery_id_mobility:7
//     },
//     5:{
//       mastery_id_strength:18,
//       mastery_id_mobility:3
//     },
//     6:{
//       mastery_id_strength:5,
//       mastery_id_mobility:3
//     },
//     7:{
//       mastery_id_strength:5,
//       mastery_id_mobility:18
//     },
//     8:{
//       mastery_id_strength:5,
//       mastery_id_mobility:5
//     },
//     9:{
//       mastery_id_strength:5,
//       mastery_id_mobility:5
//     },
//     10:{
//       mastery_id_strength:5,
//       mastery_id_mobility:9
//     },
//     11:{
//       mastery_id_strength:5,
//       mastery_id_mobility:4
//     },
//     12:{
//       mastery_id_strength:7,
//       mastery_id_mobility:4
//     },
//     13:{
//       mastery_id_strength:7,
//       mastery_id_mobility:9
//     },
//     14:{
//       mastery_id_strength:15,
//       mastery_id_mobility:5
//     },
//     15:{
//       mastery_id_strength:8,
//       mastery_id_mobility:3
//     },
//     16:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     17:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     18:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     19:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     20:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     21:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     22:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     23:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     24:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     25:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//   },
//   4:{
//     1:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     2:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     3:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     4:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     5:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     6:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     7:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     8:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     9:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     10:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     11:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     12:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     13:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     14:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     15:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     16:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     17:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     18:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//   },
//   5:{
//     1:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     2:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     3:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     4:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     5:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     6:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     7:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     8:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     9:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     10:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     11:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     12:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     13:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     14:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     15:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     16:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     17:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     18:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     19:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     20:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     21:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     22:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     23:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     24:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     25:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     26:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     27:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     28:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     29:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     30:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//   },
//   6:{
//     1:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     2:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     3:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     4:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     5:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     6:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     7:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     8:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     9:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     10:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     11:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     12:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     13:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     14:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     15:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     16:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     17:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     18:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     19:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     20:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     21:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     22:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     23:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     24:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     25:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//   },
//   7:{
//     1:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     2:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     3:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     4:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     5:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     6:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     7:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     8:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     9:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     10:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     11:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     12:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     13:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     14:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     15:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     16:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     17:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     18:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     19:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     20:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     21:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     22:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     23:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     24:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     25:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     26:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//     27:{
//       mastery_id_strength:,
//       mastery_id_mobility:
//     },
//   },
// };

exports.seed = (knex, Promise) =>{
  return knex('progressions_exercises').del()
    .then( () =>{
      //NOTE: shifts are the number of each strength/mobility exercise per progression
      const shifts = [17,27,25,18,30,25,27];
      const cutsIndexes = [0,34,88,138,174,234,284];
      return knex('exercises')
      .select()
      .then((allExercises)=>{
        let allProgressions = [];
        shifts.forEach((val,index)=>{
          let count = 1;
          for ( let i = cutsIndexes[index]; i < val+cutsIndexes[index]; i++ ) {
            let obj = {
              progression_id:index+1,
              exercise_id_strength:null,
              exercise_id_mobility:null,
              sequence_number:null
            };
            obj.exercise_id_strength = allExercises[i].exercise_id;
            obj.exercise_id_mobility = allExercises[i].exercise_id+shifts[index];
            obj.sequence_number = count;
            count++;
            allProgressions.push(obj);
          }
        })
        return allProgressions
      })
      .then((allProgressionsInSequence)=>{
        console.log('allProgressionsInSequence',allProgressionsInSequence);
        return knex('progressions_exercises')
          .insert(allProgressionsInSequence)
          .catch((err)=>{
            console.error('Seed error with progressions_exercises',err);
          })
      })
    });
  };