exports.seed = (knex, Promise)=>{
  return knex('routines').del()
    .then( ()=>{
      return knex('routines').insert([
        {routine_id: 1, stretch_sequence: 1,completed:true},
        {routine_id: 1, stretch_sequence: 2,completed:true},
        {routine_id: 1, stretch_sequence: 3,completed:true},
        {routine_id: 1, stretch_sequence: 4,completed:true},
        {routine_id: 1, stretch_sequence: 5,completed:true},
        {routine_id: 1, stretch_sequence: 6,completed:true},
        {routine_id: 1, stretch_sequence: 7,completed:true},
        {routine_id: 1, stretch_sequence: 8,completed:true},
        {routine_id: 1, stretch_sequence: 9,completed:true},
        {routine_id: 1, stretch_sequence: 10,completed:false},
        {routine_id: 1, stretch_sequence: 11,completed:false},
        {routine_id: 1, stretch_sequence: 12,completed:false},
        {routine_id: 1, stretch_sequence: 13,completed:false},
        {routine_id: 1, stretch_sequence: 14,completed:false},
        {routine_id: 1, stretch_sequence: 15,completed:false},
        {routine_id: 1, stretch_sequence: 16,completed:false},
        {routine_id: 1, stretch_sequence: 17,completed:false},
        {routine_id: 1, stretch_sequence: 18,completed:false},
        {routine_id: 1, stretch_sequence: 19,completed:false},
        {routine_id: 1, stretch_sequence: 20,completed:false},
        {routine_id: 1, stretch_sequence: 21,completed:false},
        {routine_id: 1, stretch_sequence: 22,completed:false},

        {routine_id: 4, stretch_sequence: 1,completed:true},
        {routine_id: 4, stretch_sequence: 2,completed:true},
        {routine_id: 4, stretch_sequence: 3,completed:true},
        {routine_id: 4, stretch_sequence: 4,completed:true},
        {routine_id: 4, stretch_sequence: 5,completed:true},
        {routine_id: 4, stretch_sequence: 6,completed:true},
        {routine_id: 4, stretch_sequence: 7,completed:true},
        {routine_id: 4, stretch_sequence: 8,completed:true},
        {routine_id: 4, stretch_sequence: 9,completed:true},
        {routine_id: 4, stretch_sequence: 10,completed:true},
        {routine_id: 4, stretch_sequence: 11,completed:true},
        {routine_id: 4, stretch_sequence: 12,completed:true},
        {routine_id: 4, stretch_sequence: 13,completed:true},
        {routine_id: 4, stretch_sequence: 14,completed:true},
        {routine_id: 4, stretch_sequence: 15,completed:true},
        {routine_id: 4, stretch_sequence: 16,completed:true},
        {routine_id: 4, stretch_sequence: 17,completed:false},
        {routine_id: 4, stretch_sequence: 18,completed:true},
        {routine_id: 4, stretch_sequence: 19,completed:true},
        {routine_id: 4, stretch_sequence: 20,completed:false},
        {routine_id: 4, stretch_sequence: 21,completed:false},
        {routine_id: 4, stretch_sequence: 22,completed:false},
        {routine_id: 4, stretch_sequence: 23,completed:false},

        {routine_id: 5, stretch_sequence: 1,completed:true},
        {routine_id: 5, stretch_sequence: 2,completed:false},
        {routine_id: 5, stretch_sequence: 3,completed:false},
        {routine_id: 5, stretch_sequence: 4,completed:false},
        {routine_id: 5, stretch_sequence: 5,completed:false},
        {routine_id: 5, stretch_sequence: 6,completed:false},
        {routine_id: 5, stretch_sequence: 7,completed:false},
        {routine_id: 5, stretch_sequence: 8,completed:false},
        {routine_id: 5, stretch_sequence: 9,completed:false},
        {routine_id: 5, stretch_sequence: 10,completed:false},
        {routine_id: 5, stretch_sequence: 11,completed:false},
        {routine_id: 5, stretch_sequence: 12,completed:false},
        {routine_id: 5, stretch_sequence: 13,completed:false},
        {routine_id: 5, stretch_sequence: 14,completed:false},
        {routine_id: 5, stretch_sequence: 15,completed:false},
        {routine_id: 5, stretch_sequence: 16,completed:false},
        {routine_id: 5, stretch_sequence: 17,completed:false},

        {routine_id: 7, stretch_sequence: 1,completed:true},
        {routine_id: 7, stretch_sequence: 2,completed:true},
        {routine_id: 7, stretch_sequence: 3,completed:true},
        {routine_id: 7, stretch_sequence: 4,completed:true},
        {routine_id: 7, stretch_sequence: 5,completed:true},
        {routine_id: 7, stretch_sequence: 6,completed:true},
        {routine_id: 7, stretch_sequence: 7,completed:true},
        {routine_id: 7, stretch_sequence: 8,completed:false},
        {routine_id: 7, stretch_sequence: 9,completed:false},
        {routine_id: 7, stretch_sequence: 10,completed:false},
        {routine_id: 7, stretch_sequence: 11,completed:false},
        {routine_id: 7, stretch_sequence: 12,completed:false},
        {routine_id: 7, stretch_sequence: 13,completed:false},
        {routine_id: 7, stretch_sequence: 14,completed:false},
        {routine_id: 7, stretch_sequence: 15,completed:false},
        {routine_id: 7, stretch_sequence: 16,completed:false},
        {routine_id: 7, stretch_sequence: 17,completed:false},

        {routine_id: 9, stretch_sequence: 1,completed:true},
        {routine_id: 9, stretch_sequence: 2,completed:true},
        {routine_id: 9, stretch_sequence: 3,completed:true},
        {routine_id: 9, stretch_sequence: 4,completed:true},
        {routine_id: 9, stretch_sequence: 5,completed:true},
        {routine_id: 9, stretch_sequence: 6,completed:true},
        {routine_id: 9, stretch_sequence: 7,completed:true},
        {routine_id: 9, stretch_sequence: 8,completed:true},
        {routine_id: 9, stretch_sequence: 9,completed:true},
        {routine_id: 9, stretch_sequence: 10,completed:true},
        {routine_id: 9, stretch_sequence: 11,completed:true},
        {routine_id: 9, stretch_sequence: 12,completed:true},
        {routine_id: 9, stretch_sequence: 13,completed:true},
        {routine_id: 9, stretch_sequence: 14,completed:true},
        {routine_id: 9, stretch_sequence: 15,completed:false},
        {routine_id: 9, stretch_sequence: 16,completed:false},
        {routine_id: 9, stretch_sequence: 17,completed:false},


      ]);
    });
};
